### ISSUE TITLE
Asking for training code

### ISSUE THREAD

**Issue by Yingjia-Wan** [mair-lab/mapl#1]
Dear MAPL authors,

Thank you for the wonderful work! I am trying to reference the MAPL architecture to build a multilingual model for other modalities of data. I noticed that the MAPL Git repo does not contain the code file for training the architecture, and was wondering if you can provide it for adaptation. Many thanks.

Best,
Yingjia

**Comment by oscmansan** [comment]
Dear Yingjia,

Thank you so much for your interest in our work! I uploaded the training scripts to the `training` branch for now. I'll eventually merge it into the `main` branch.

Good luck with your project!

Best,
Oscar
